// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_emO58_tPqzZtn8KJ2JOaYLgE5LO2CAk',
    appId: '1:111787998360:web:249856e5308266fccea4ed',
    messagingSenderId: '111787998360',
    projectId: 'roomfinanceapp',
    authDomain: 'roomfinanceapp.firebaseapp.com',
    storageBucket: 'roomfinanceapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6KcoUDTnK1q1W6wSScfxYWyuMMSsndWY',
    appId: '1:111787998360:android:9cca186d402d9fabcea4ed',
    messagingSenderId: '111787998360',
    projectId: 'roomfinanceapp',
    storageBucket: 'roomfinanceapp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAq7skIWQkQ1ri9atIvNM7KctW8SYvuhU',
    appId: '1:111787998360:ios:038150036372759dcea4ed',
    messagingSenderId: '111787998360',
    projectId: 'roomfinanceapp',
    storageBucket: 'roomfinanceapp.firebasestorage.app',
    iosBundleId: 'com.example.roomFinanceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAq7skIWQkQ1ri9atIvNM7KctW8SYvuhU',
    appId: '1:111787998360:ios:038150036372759dcea4ed',
    messagingSenderId: '111787998360',
    projectId: 'roomfinanceapp',
    storageBucket: 'roomfinanceapp.firebasestorage.app',
    iosBundleId: 'com.example.roomFinanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_emO58_tPqzZtn8KJ2JOaYLgE5LO2CAk',
    appId: '1:111787998360:web:ddcd183782ee2b1acea4ed',
    messagingSenderId: '111787998360',
    projectId: 'roomfinanceapp',
    authDomain: 'roomfinanceapp.firebaseapp.com',
    storageBucket: 'roomfinanceapp.firebasestorage.app',
  );
}
